static const char black[]       = "#1e1e2e";
static const char gray2[]       = "#313244"; // unfocused window border
static const char gray3[]       = "#585b70";
static const char gray4[]       = "#181825";
static const char blue[]        = "#89b4fa";  // focused window border
static const char green[]       = "#a6e3a1";
static const char red[]         = "#f38ba8";
static const char orange[]      = "#fab387";
static const char yellow[]      = "#f9e2af";
static const char pink[]        = "#f5c2e7";
static const char sky[]         = "#89dceb";
static const char teal[]        = "#94e2d5";
static const char mauve[]       = "#cba6f7";
static const char col_borderbar[]  = "#1e1e2e"; // inner border
static const char white[] = "#f8f8f2";
