#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse autofocus \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_opacity on \
  split_ratio 0.50 \
  split_type auto \
  auto_balance on \
  top_padding 06 \
  bottom_padding 06 \
  left_padding 06 \
  right_padding 06 \
  window_gap 06 \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  external_bar all:40:0

yabai -m rule --add app="^(Calculator|Software Update|Dictionary|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store|Alfred)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded..."
