#!/usr/bin/env bash

DIR="$HOME/.config/hypr"
source "$DIR"/theme/current.bash

bg=${background:1}  fg=${foreground:1}
red=${color1:1}     green=${color2:1}    yellow=${color3:1}
blue=${color4:1}    magenta=${color5:1}  cyan=${color6:1}
alpha='00000000'

swaylock -f \
	\
	--ignore-empty-password \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	--color ${bg}E6 \
	--font 'JetBrainsMono Nerd Font Mono' --font-size 18 \
	--key-hl-color ${green} \
	--caps-lock-key-hl-color ${blue} \
	--bs-hl-color ${red} \
	--caps-lock-bs-hl-color ${red} \
	--indicator-radius 120 \
	--indicator-thickness 10 \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	--layout-bg-color ${cyan} \
	--layout-border-color ${cyan} \
	--layout-text-color ${bg} \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	--ring-color ${cyan} \
	--ring-clear-color ${bg} \
	--ring-caps-lock-color ${magenta} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${red} \
	--separator-color ${bg} \
	--text-color ${fg} \
	--text-clear-color ${fg} \
	--text-caps-lock-color ${fg} \
	--text-ver-color ${bg} \
	--text-wrong-color ${bg}
