#!/usr/bin/env bash

GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
QT_QPA_PLATFORM=xcb

_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
  if [[ `pidof ${_prs}` ]]; then
    killall -9 ${_prs}
  fi
done

if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

~/.config/hypr/scripts/wallpaper &
~/.config/hypr/scripts/gtkthemes &
~/.config/hypr/scripts/notifications &
~/.config/hypr/scripts/statusbar &
nm-applet --indicator &
