# Path
export PATH="$PATH:$HOME/.bun/bin:$HOME/.composer/vendor/bin:$HOME/.spicetify:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.config/emacs/bin/:$HOME/Library/Python/3.12/bin"

# Path to OMZ installation.
export ZSH="$HOME/.oh-my-zsh"

# Editor env variables
export EDITOR=nvim
export SUDO_EDITOR=nvim

# Theme
ZSH_THEME="gallifrey"

# Plugins
plugins=(brew command-not-found cp fast-syntax-highlighting git python rails ruby zsh-autosuggestions)

# OMZ script
source $ZSH/oh-my-zsh.sh

# Aliases
alias ls="eza --color=always --icons --group-directories-first"
alias la="eza -lah --color=always --icons --group-directories-first"
alias lt="eza -aT --color=always --icons --group-directories-first"
alias lh="eza -la --color=always --icons --group-directories-first | grep '^\.'"
alias gs="git status"
alias ga="git add -A"
alias gc="git commit -m"
alias gp="git push"
alias cp="cpv"
alias vim="nvim"
alias ar="php artisan"
alias rm="trash"
alias bin="brew install"

# NVM
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# GPG stuff
export GPG_TTY=$(tty)

# Misc
eval "$(zoxide init zsh)"
eval "$(rbenv init -)"
